apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    processors:
      - add_cloud_metadata:

    output.elasticsearch:
      hosts: ['http://es-entrypoint:9200']
      index: "metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"
    setup.kibana:
      host: 'kibana-entrypoint:5601'
    setup.template:
      name: 'metricbeat'
      pattern: 'metricbeat-*'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-modules
  labels:
    k8s-app: metricbeat
data:
  aws.yml: |-
    - module: aws
      period: 300s
      regions:
        - ap-southeast-2
      # role_arn: arn:aws:iam::264100014405:role/ELKIntegrationRole
      access_key_id: ASIAT27MWNFCYRXF3PGP
      secret_access_key: k5octw5Nq1QOqnVG2fFe7zM8yRNXHaCgFFHiTKck
      session_token: IQoJb3JpZ2luX2VjEHoaDmFwLXNvdXRoZWFzdC0yIkcwRQIhAKnrW/eJl3wn0EIDgRRVil2B6mpKYJBkrEn71SnXU53VAiAgnEgvqopYPufQv+PfG7uvUwj83TIzawp/lNdUvp64DSqMAwhzEAEaDDI2NDEwMDAxNDQwNSIMJY9k6GmzW4NIkt1RKukCMPXUB7OfFOh1AkxTXaPbh5SmK4b0SrfoLLBy1xTKzMRwf/V50cKN4e3Izq5xnPQrNfUuB6zXtGP6Lpqm3LPPx2XJfHNU9EqPnMDL+oFZwAgL5wo+nYTRB6yNve5mIBiXioes1OPcYlhX6QZcBzSf6BJVrzp+zCGlYUl11YZklg86rq4+70ov2DMttldxj8k4+VszNgaEC0UQQJflNSVzoqA77murlDWnFLec1cz8whXe6NbW6g7IfBSjjTP7ENk+/DFtE+9PXpyZBLrDkPH63Zlbnl4EllNiI+Jqm04FHpsStLRFziTAd8m69Ofv86BRc9J3avRDJ1uxVF+bFHeCQDs9XuA9hfrFgLO4qg+7EQXSWpu/tHcHsKUkHZfLJ6d+KUEeD//y+2BQve7pYuE/UkLotv2ZTOIvpSjOIeXrtsBoFeH1BMCoi8fI82GNzRY0aSNn2snXx6M3oZPX8bUgSXaSfO9Ins7fEjDf6s+HBjqmAcB5vVLIW95ZRGzpKyEJc+NsCT0lXmiTgQHXEkWLGa4Mq488hRJ/KnpiFF+RhjvzOECyPi2/EmO4p897s5GktLUS6K/l+jUj1NPek7QciIUFlW0FdTf2URZ2yUv1jW/D/NDKf5t5iivHOBunVZJo/DFNvV+bNWFWvIiJzEkCgvHqLSjrmObmaB09uzckRVjBtRU4tU7vveupqKtcjmcAR9jOYjBPtks=
      metricsets:
        # - elb
        # - natgateway
        # - rds
        # - transitgateway
        # - usage
        # - vpn
        - cloudwatch
        # - lambda
      metrics:
        - namespace: AWS/DynamoDB
        - namespace: AWS/Lambda
        - namespace: AWS/Events
        - namespace: AWS/AppSync
        - namespace: AWS/ApiGateway
        - namespace: AWS/RDS
    # - module: aws
    #   role_arn: arn:aws:iam::264100014405:role/ELKIntegrationRole
    #   period: 24h
    #   regions:
    #     - ap-southeast-2
    #   metricsets:
    #     - billing
---
# Deploy a Metricbeat instance per node for node metrics retrieval
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
spec:
  selector:
    matchLabels:
      k8s-app: metricbeat
  template:
    metadata:
      labels:
        k8s-app: metricbeat
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: metricbeat
        image: elastic/metricbeat:7.11.1
        env:
        - name: ELASTICSEARCH_HOSTS
          value: es-entrypoint
        resources:
          limits:
            memory: 2000Mi
          requests:
            cpu: 1
            memory: 1000Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/metricbeat/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 0640
            name: metricbeat-daemonset-config
        - name: modules
          configMap:
            defaultMode: 0640
            name: metricbeat-daemonset-modules
