---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - eks-console-dashboard-full-access-group
    - rolearn: <>
      username: ssoadmin
      groups:
        - system:masters
        - system:bootstrappers
        - system:nodes
        - eks-console-dashboard-full-access-group