kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled

kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
  labels:
data:
  output.conf: |
    [OUTPUT]
        Name cloudwatch
        Match   *
        region <ap-southeast-2>
        log_group_name elk-fluent-bit-cloudwatch
        log_stream_prefix from-elk-fluent-bit-
        auto_create_group true